name: Build and Deploy Static Site

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build Hono project
      run: npm run build
      
    - name: Start server for static generation
      run: |
        # Start the server in background
        npx wrangler pages dev dist --port 3000 --ip 0.0.0.0 &
        SERVER_PID=$!
        
        # Wait for server to start
        echo "Waiting for server to start..."
        for i in {1..30}; do
          if curl -f http://localhost:3000 >/dev/null 2>&1; then
            echo "Server is ready!"
            break
          fi
          sleep 2
        done
        
        # Generate static HTML files
        mkdir -p static-export
        
        # Main pages
        curl -s http://localhost:3000/ > static-export/index.html
        curl -s http://localhost:3000/vergelijken > static-export/vergelijken.html
        curl -s http://localhost:3000/kopen > static-export/kopen.html
        curl -s http://localhost:3000/kosten > static-export/kosten.html
        curl -s http://localhost:3000/subsidie > static-export/subsidie.html
        curl -s http://localhost:3000/blog > static-export/blog.html
        curl -s http://localhost:3000/faq > static-export/faq.html
        curl -s http://localhost:3000/over-ons > static-export/over-ons.html
        
        # Guide pages
        mkdir -p static-export/gids
        curl -s http://localhost:3000/gids/kopers-gids > static-export/gids/kopers-gids.html
        curl -s http://localhost:3000/gids/installatie > static-export/gids/installatie.html
        curl -s http://localhost:3000/gids/onderhoud-garantie > static-export/gids/onderhoud-garantie.html
        curl -s http://localhost:3000/gids/besparing-maximaliseren > static-export/gids/besparing-maximaliseren.html
        
        # Blog pages
        mkdir -p static-export/blog
        curl -s http://localhost:3000/blog/energieonafhankelijkheid > static-export/blog/energieonafhankelijkheid.html
        
        # Brand pages
        curl -s http://localhost:3000/zonneplan-thuisbatterij > static-export/zonneplan-thuisbatterij.html
        curl -s http://localhost:3000/growatt-thuisbatterij > static-export/growatt-thuisbatterij.html
        
        # Product pages
        mkdir -p static-export/merken
        curl -s http://localhost:3000/merken/growatt-arb-10 > static-export/merken/growatt-arb-10.html || echo "Page not found: growatt-arb-10"
        curl -s http://localhost:3000/merken/dyness-powerwall-b4850 > static-export/merken/dyness-powerwall-b4850.html || echo "Page not found: dyness-powerwall-b4850"
        curl -s http://localhost:3000/merken/victron-multiplus > static-export/merken/victron-multiplus.html || echo "Page not found: victron-multiplus"
        curl -s http://localhost:3000/merken/homewizard-p1 > static-export/merken/homewizard-p1.html || echo "Page not found: homewizard-p1"
        curl -s http://localhost:3000/merken/zonneplan-battery > static-export/merken/zonneplan-battery.html || echo "Page not found: zonneplan-battery"
        
        # Copy static assets
        cp -r public/* static-export/ 2>/dev/null || true
        
        # Stop the server
        kill $SERVER_PID 2>/dev/null || true
        
    - name: Copy hosting configuration files
      run: |
        # Copy .htaccess, robots.txt, sitemap.xml from existing static-export
        cp static-export/.htaccess static-export/.htaccess.bak 2>/dev/null || true
        cp static-export/robots.txt static-export/robots.txt.bak 2>/dev/null || true  
        cp static-export/sitemap.xml static-export/sitemap.xml.bak 2>/dev/null || true
        cp static-export/DEPLOYMENT_README.md static-export/DEPLOYMENT_README.md.bak 2>/dev/null || true
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: thuisbatterijwereld-static-site
        path: static-export/
        retention-days: 30
        
    - name: Deploy to GitHub Pages (Optional)
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./static-export
        cname: thuisbatterijwereld.nl